.TH qthread_id 3 "NOVEMBER 2006" libqthread "libqthread"
.SH NAME
\fBqthread_id\fR \- returns the qthread's unique ID number
.SH SYNOPSIS
.B #include <qthread/qthread.h>

.I unsigned int
.br
\fBqthread_id\fR(qthread_t *\fIt\fR);
.SH DESCRIPTION
This function returns the unique identifier associated with the qthread
\fIt\fR. This is used mostly for debugging, as the qthread_t pointer itself is
a valid temporally-unique identifier (the qthread_t structures can be re-used).
Unless otherwise configured, the qthread library assigns thread ids only when
they are asked for. Generally they are monotonically increasing values, but the
value can wrap around after UINT_MAX threads.
.SH RETURN VALUE
On success, the thread's identifying number is returned.
.SH "SEE ALSO"
.BR qthread_retloc (3),
.BR qthread_self (3),
.BR qthread_shep (3),
.BR qthread_stackleft (3)
