.TH qthread_sorted_sheps 3 "March 2009" libqthread "libqthread"
.SH NAME
\fBqthread_sorted_sheps\fR, \fBqthread_sorted_sheps_remote\fR \- returns a list
of other shepherds, sorted by their distance
.SH SYNOPSIS
.B #include <qthread/qthread.h>

.I const qthread_shepherd_id_t *
.br
\fBqthread_sorted_sheps\fR(const qthread_t *\fIt\fR);
.PP
.I const qthread_shepherd_id_t *
.br
\fBqthread_sorted_sheps_remote\fR(const qthread_shepherd_id_t \fIsrc\fR);
.SH DESCRIPTION
This function returns a list of shepherds, sorted by their distance from either
the shepherd of thread \fIt\fR or the specified shepherd \fIsrc\fR. This list
is an array of qthread_shepherd_id_t objects with a length of one less than the
number of shepherds (as determined by \fBqthread_num_shepherds\fR()). The
source shepherd is not included in the list.
.PP
The returned array \fImust not\fR be altered.
.SH RETURN VALUE
These functions will return either a pointer to an array of
qthread_shepherd_id_t objects, or NULL if the specified shepherd is either
invalid or does not have a specific CPU affinity.
