.TH qthread_shep 3 "NOVEMBER 2006" libqthread "libqthread"
.SH NAME
\fBqthread_shep\fR \- returns the qthread's shepherd ID
.SH SYNOPSIS
.B #include <qthread/qthread.h>

.I qthread_shepherd_id_t
.br
\fBqthread_shep\fR(qthread_t *\fIt\fR);
.SH DESCRIPTION
This function returns the shepherd identifier of the qthread \fIt\fR. If \fIt\fR is NULL, the shepherd identifier is looked up using an internal mechanism; usually \fBpthread_getspecific\fR().
.PP
Note that
.RS
.PP
\fBqthread_shep\fR(\fBNULL\fR)
.RE
.PP
is slightly more efficient than
.RS
.PP
\fBqthread_shep\fR(\fBqthread_self\fR())
.RE
.SH "RETURN VALUE"
This function either returns the ID number of the shepherd of the calling function, or returns NO_SHEPHERD.
.SH "SEE ALSO"
.BR qthread_retloc (3),
.BR qthread_self (3),
.BR qthread_stackleft (3),
.BR qthread_id (3)
