.TH qthread_stackleft 3 "NOVEMBER 2006" libqthread "libqthread"
.SH NAME
\fBqthread_stackleft\fR \- returns the amount of space left in the thread's allocated stack
.SH SYNOPSIS
.B #include <qthread/qthread.h>

.I size_t
.br
\fBqthread_stackleft\fR(qthread_t *\fIt\fR);
.SH DESCRIPTION
This function returns the number of bytes left in the stack. The argument,
\fIt\fR, MUST be the current qthread for the answer to make sense.
.SH "RETURN VALUE"
If \fIt\fR is non-null, it returns the number of bytes left in the stack, accurate to a small margin (on the order of 10 bytes). If \fIt\fR is NULL, \fBqthread_stackleft\fR() returns 0.
.SH "SEE ALSO"
.BR qthread_id (3),
.BR qthread_retloc (3),
.BR qthread_self (3),
.BR qthread_shep (3)
