.TH future_exit 3 "NOVEMBER 2006" libqthread "libqthread"
.SH NAME
\fBfuture_exit\fR \- finalize a future computation
.SH SYNOPSIS
.B #include <qthread/futurelib.h>

.I void
.br
\fBfuture_exit\fR(qthread_t *\fIme\fR);
.PP

.SH DESCRIPTION
Threads created as futures must call this function as their final action
before termination in order to release resources.
.PP
The argument is the qthread pointer of the terminating thread, which
can be found out using \fBqthread_self\fR().
.SH "SEE ALSO"
.BR future_join_all (3),
.BR future_init (3),
.BR future_exit (3),
.BR future_yeild (3),
.BR future_acquire (3)
