.TH qthread_self 3 "NOVEMBER 2006" libqthread "libqthread"
.SH NAME
\fBqthread_self\fR \- retrieve the qthread_t pointer for the current thread
.SH SYNOPSIS
.B #include <qthread/qthread.h>

.I qthread_t *
.br
\fBqthread_self\fR(void);
.SH DESCRIPTION
This function allows a qthread to retrieve its qthread_t pointer, usually if
the pointer has been lost for some reason.
.PP
This currently relies on \fBpthread_self\fR(), and so on some architectures may
cause a context-switch into the kernel.
.SH "RETURN VALUE"
\fBqthread_self\fR() will return either a pointer to the qthread_t structure
associated with the calling qthread, or if called from a non-qthread, will
return NULL.
.SH "SEE ALSO"
.BR qthread_id (3),
.BR qthread_arg (3),
.BR qthread_shep (3)
