.TH qthread_join 3 "NOVEMBER 2006" libqthread "libqthread"
.SH NAME
\fBqthread_join\fR \- wait for a qthread to finish
.SH SYNOPSIS
.B #include <qthread/qthread.h>

.I void
.br
\fBqthread_join\fR(qthread_t *\fIme\fR, qthread_t *\fIwaitfor\fR);
.SH DESCRIPTION
This is the join function, which will only return once the \fIwaitfor\fR thread
has finished executing.
.PP
\fBqthread_join\fR() will work whether called from within a qthread or not. If
not called from within a qthread, pass it \fBNULL\fR for the \fIme\fR argument.
It relies on a \fBqthread_lock\fR() and \fBqthread_unlock\fR() operation on the
address of the \fBqthread_t\fR data structure (the user CAN muck with that, but
it's not recommended), so it is a blocking join that will not take processing
time for long waits.
