.TH qthread_init 3 "NOVEMBER 2006" libqthread "libqthread"
.SH NAME
\fBqthread_init\fR \- initialize the qthread library
.SH SYNOPSIS
.B #include <qthread/qthread.h>

.I void
.br
\fBqthread_init\fR(const int \fInshepherds\fR);
.SH DESCRIPTION
Use this function to initialize the qthreads environment before spawning any
qthreads or using any of the qthreads locking/FEB functions. The number of
shepherd pthreads that will execute qthreads is specified with
\fInshepherds\fR.
.SH "SEE ALSO"
.BR qthread_finalize (3)
